### ISSUE TITLE
What's the Purpose of Timestamp column in tblStudent?

### ISSUE THREAD

**Issue by jrola03** [arthurdistor/StudentRegistrationSystem#13]
Ano purpose ng timestamp? Kung date at time ang kukunin bat di nalang nag DATETIME column? Or varchar mas ok hahaha para mas madali mag insert hahah skl

**Comment by arthurdistor** [comment]
Using the timestamp datatype, it will automatically insert date and time to the column after the row was updated without programmatically coding it. Close this issue if I suffice your question.

P.s. You can use the MS Teams or other messaging device to as a question. The issue tab here must be focus on the issue on the system itself.
